### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [recovered]

### ISSUE THREAD

**Issue by JasonWu0506** [ondrajz/go-callvis#180]
go-callvis 
v0.7.0 built from git (unknown)
run go-callvis ${package}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1024ec084]

goroutine 61 [running]:
go/types.(*Checker).handleBailout(0x14000034200, 0x1400013fb98)
	/opt/homebrew/opt/go/libexec/src/go/types/check.go:367 +0x9c
panic({0x102a27f60?, 0x102df17b0?})
	/opt/homebrew/opt/go/libexec/src/runtime/panic.go:770 +0x124
go/types.(*StdSizes).Sizeof(0x0, {0x102ac4650, 0x102df84e0})
	/opt/homebrew/opt/go/libexec/src/go/types/sizes.go:228 +0x314
go/types.(*Config).sizeof(...)
	/opt/homebrew/opt/go/libexec/src/go/types/sizes.go:333
go/types.representableConst.func1({0x102ac4650?, 0x102df84e0?})
	/opt/homebrew/opt/go/libexec/src/go/types/const.go:76 +0x9c
go/types.representableConst({0x102ac7888, 0x102e44a20}, 0x14000034200, 0x102df84e0, 0x1400013df98)
	/opt/homebrew/opt/go/libexec/src/go/types/const.go:92 +0x138
go/types.(*Checker).representation(0x14000034200, 0x140004eb180, 0x102df84e0)
	/opt/homebrew/opt/go/libexec/src/go/types/const.go:256 +0x68
go/types.(*Checker).implicitTypeAndValue(0x14000034200, 0x140004eb180, {0x102ac4650, 0x102df84e0})
	/opt/homebrew/opt/go/libexec/src/go/types/expr.go:375 +0x304
go/types.(*Checker).convertUntyped(0x14000034200, 0x140004eb180, {0x102ac4650, 0x102df84e0})
	/opt/homebrew/opt/go/libexec/src/go/types/const.go:289 +0x30
go/types.(*Checker).matchTypes(0x14000034200, 0x140004eb140, 0x140004eb180)
	/opt/homebrew/opt/go/libexec/src/go/types/expr.go:926 +0x7c

**Comment by fuchao1999** [comment]
go v1.22 
go-callvis v0.7.0 built from git (unknown)


go-callvis .
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x95d56f]

goroutine 228 [running]:
go/types.(*Checker).handleBailout(0xc000550600, 0xc000a7fbd0)
        D:/Go/src/go/types/check.go:367 +0x88
panic({0xc628a0?, 0x10eaf50?})
        D:/Go/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xdc4a38, 0x10f11c0})
        D:/Go/src/go/types/sizes.go:228 +0x30f
go/types.(*Config).sizeof(...)
        D:/Go/src/go/types/sizes.go:333
go/types.representableConst.func1({0xdc4a38?, 0x10f11c0?})
        D:/Go/src/go/types/const.go:76 +0x9e
go/types.representableConst({0xdc7a38, 0x10c8990}, 0xc000550600, 0x10f11c0, 0xc000a7dd70)
        D:/Go/src/go/types/const.go:92 +0x192
go/types.(*Checker).representation(0xc000550600, 0xc00039dd40, 0x10f11c0)
        D:/Go/src/go/types/const.go:256 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc000550600, 0xc00039dd40, {0xdc4a38, 0x10f11c0})
        D:/Go/src/go/types/expr.go:375 +0x2d7
go/types.(*Checker).assignment(0xc000550600, 0xc00039dd40, {0xdc4a38, 0x10f11c0}, {0xcec92b, 0xe})
        D:/Go/src/go/types/assignments.go:52 +0x2e5
go/types.(*Checker).exprInternal(0xc000550600, 0x0, 0xc00039dd40, {0xdc6c00, 0xc00039c780}, {0xdc4a88, 0xc0003f6070})
        D:/Go/src/go/types/expr.go:1175 +0x267a
go/types.(*Checker).rawExpr(0xc000550600, 0x0, 0xc00039dd40, {0xdc6c00?, 0xc00039c780?}, {0xdc4a88?, 0xc0003f6070?}, 0x0)
        D:/Go/src/go/types/expr.go:979 +0x19e
go/types.(*Checker).exprWithHint(0xc000550600, 0xc00039dd40, {0xdc6c00, 0xc00039c780}, {0xdc4a88, 0xc0003f6070})
        D:/Go/src/go/types/expr.go:1563 +0x65
go/types.(*Checker).indexedElts(0xc000550600, {0xc000550000, 0x1b, 0xc000a7ee30?}, {0xdc4a88, 0xc0003f6070}, 0xffffffffffffffff)
        D:/Go/src/go/types/index.go:453 +0x129
go/types.(*Checker).exprInternal(0xc000550600, 0x0, 0xc00039d600, {0xdc6c00, 0xc00039cf40}, {0x0, 0x0})
        D:/Go/src/go/types/expr.go:1247 +0x10dd
go/types.(*Checker).rawExpr(0xc000550600, 0x0, 0xc00039d600, {0xdc6c00?, 0xc00039cf40?}, {0x0?, 0x0?}, 0x0)
        D:/Go/src/go/types/expr.go:979 +0x19e
go/types.(*Checker).expr(0xc000550600, 0x0?, 0xc00039d600, {0xdc6c00?, 0xc00039cf40?})
        D:/Go/src/go/types/expr.go:1513 +0x30
go/types.(*Checker).varDecl(0xc000550600, 0xc000b03260, {0xc000306188, 0x1, 0x1}, {0x0, 0x0}, {0xdc6c00, 0xc00039cf40})
        D:/Go/src/go/types/decl.go:521 +0x17b
go/types.(*Checker).objDecl(0xc000550600, {0xdce798, 0xc000b03260}, 0x0)
        D:/Go/src/go/types/decl.go:194 +0x9e5
go/types.(*Checker).packageObjects(0xc000550600)
        D:/Go/src/go/types/resolver.go:693 +0x4dd
go/types.(*Checker).checkFiles(0xc000550600, {0xc000306008, 0x1, 0x1})
        D:/Go/src/go/types/check.go:408 +0x1a5
go/types.(*Checker).Files(...)
        D:/Go/src/go/types/check.go:372
golang.org/x/tools/go/packages.(*loader).loadPackage(0xc00019c000, 0xc000747500)
        F:/Workspaces/GoLand/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:1052 +0xa72
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
        F:/Workspaces/GoLand/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:851 +0x1a9
sync.(*Once).doSlow(0x0?, 0x0?)
        D:/Go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        D:/Go/src/sync/once.go:65
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x0?, 0xc000b45fd0?)
        F:/Workspaces/GoLand/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:839 +0x4a
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0x0?)
        F:/Workspaces/GoLand/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:846 +0x26
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1 in goroutine 168
        F:/Workspaces/GoLand/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:845 +0x94

**Comment by starZane** [comment]
It seems that only go1.22 version will report this error. I tried to change to go1.21 version and compiled it and it worked normally.

**Comment by lichenglife** [comment]
After I switched to go1.21.2, I still not work

**Comment by bkane-msft** [comment]
I'm getting a similar error trying to get the callgraph for https://github.com/bbkane/envelope/

```
$ go version
go version go1.23.1 linux/amd64
```

```
master 21:51:34.138 PDT pop-os:~/Git-GH/envelope
$ go-callvis go.bbkane.com/envelope
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6217ef]

goroutine 231 [running]:
go/types.(*Checker).handleBailout(0xc000021a40, 0xc00036bbf0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/check.go:404 +0x88
panic({0xad1ca0?, 0x100fdc0?})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/runtime/panic.go:785 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xc567c0, 0x1016cc0})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/sizes.go:229 +0x30f
go/types.(*Config).sizeof(...)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/sizes.go:334
go/types.representableConst.func1({0xc567c0?, 0x1016cc0?})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/const.go:77 +0x86
go/types.representableConst({0xc5a200, 0x1067040}, 0xc000021a40, 0x1016cc0, 0xc00036aa30)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/const.go:93 +0x173
go/types.(*Checker).representation(0xc000021a40, 0xc000115540, 0x1016cc0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/const.go:257 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc000021a40, 0xc000115540, {0xc567c0, 0x1016cc0})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/expr.go:377 +0x2d7
go/types.(*Checker).convertUntyped(0xc000021a40, 0xc000115540, {0xc567c0, 0x1016cc0})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/const.go:290 +0x3f
go/types.(*Checker).matchTypes(0xc000021a40, 0xc000115280, 0xc000115540)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/expr.go:928 +0x79
go/types.(*Checker).binary(0xc000021a40, 0xc000115280, {0xc58b70, 0xc0004600f0}, {0xc58c30, 0xc0005a61a0}, {0xc59170, 0xc0005a61c0}, 0x28, 0x38f)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/expr.go:802 +0x166
go/types.(*Checker).exprInternal(0xc000021a40, 0x0, 0xc000115280, {0xc58b70, 0xc0004600f0}, {0x0, 0x0})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/expr.go:1452 +0x206
go/types.(*Checker).rawExpr(0xc000021a40, 0x0, 0xc000115280, {0xc58b70?, 0xc0004600f0?}, {0x0?, 0x0?}, 0x0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/expr.go:981 +0x18c
go/types.(*Checker).expr(0xc000021a40, 0xc56b58?, 0xc000115280, {0xc58b70?, 0xc0004600f0?})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/expr.go:1549 +0x30
go/types.(*Checker).stmt(0xc000021a40, 0x0, {0xc58f90, 0xc000114100})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/stmt.go:579 +0xcea
go/types.(*Checker).stmtList(0xc000021a40, 0x0, {0xc0005a63c0?, 0x5e9c60?, 0xc000021a40?})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/stmt.go:121 +0x85
go/types.(*Checker).funcBody(0xc000021a40, 0xc58c30?, {0xc0002080a0?, 0x3?}, 0xc000114f40, 0xc000460180, {0x0?, 0x0?})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/stmt.go:41 +0x2f3
go/types.(*Checker).funcDecl.func1()
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/decl.go:888 +0x3a
go/types.(*Checker).processDelayed(0xc000021a40, 0x0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/check.go:516 +0x15c
go/types.(*Checker).checkFiles(0xc000021a40, {0xc0000b6000, 0x1, 0x1})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/check.go:462 +0x17e
go/types.(*Checker).Files(0xc0001da0e0?, {0xc0000b6000?, 0xc0000220c0?, 0x6?})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/check.go:422 +0x75
golang.org/x/tools/go/packages.(*loader).loadPackage(0xc0001da0e0, 0xc000563b90)
        /home/bbkane/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:1052 +0xa32
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
        /home/bbkane/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:851 +0x1a9
sync.(*Once).doSlow(0x2e73776f646e6977?, 0x2209090a2c226f67?)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/sync/once.go:76 +0xb4
sync.(*Once).Do(...)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/sync/once.go:67
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x5f68746170220909?, 0x2e73776f646e6977?)
        /home/bbkane/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:839 +0x3b
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0x90a2c226f672e74?)
        /home/bbkane/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:846 +0x26
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1 in goroutine 169
        /home/bbkane/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:845 +0x94
```

**Comment by bbkane** [comment]
I'm getting a similar panic when I try to get the callgraph for https://github.com/bbkane/envelope/

```
$ go-callvis -version
v0.7.0 built from git (unknown)
```

```
master:* 21:57:34.636 PDT pop-os:~/Git-GH/envelope
$ go-callvis go.bbkane.com/envelope
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6217ef]

goroutine 317 [running]:
go/types.(*Checker).handleBailout(0xc000a8d180, 0xc00071fbf0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/check.go:404 +0x88
panic({0xad1ca0?, 0x100fdc0?})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/runtime/panic.go:785 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xc567c0, 0x1016cc0})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/sizes.go:229 +0x30f
go/types.(*Config).sizeof(...)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/sizes.go:334
go/types.representableConst.func1({0xc567c0?, 0x1016cc0?})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/const.go:77 +0x86
go/types.representableConst({0xc5a200, 0x1067040}, 0xc000a8d180, 0x1016cc0, 0xc00071eea0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/const.go:93 +0x173
go/types.(*Checker).representation(0xc000a8d180, 0xc000115040, 0x1016cc0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/const.go:257 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc000a8d180, 0xc000115040, {0xc567c0, 0x1016cc0})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/expr.go:377 +0x2d7
go/types.(*Checker).assignment(0xc000a8d180, 0xc000115040, {0xc567c0, 0x1016cc0}, {0xb73aaa, 0x10})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/assignments.go:70 +0x451
go/types.(*Checker).initVar(0xc000a8d180, 0xc0009a5740, 0xc000115040, {0xb73aaa, 0x10})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/assignments.go:181 +0x428
go/types.(*Checker).initVars(0xc000a8d180, {0xc00022e278, 0x1, 0x0?}, {0xc000514070, 0xb6dba3?, 0x3?}, {0xc58ed0, 0xc000130ae0})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/assignments.go:399 +0x638
go/types.(*Checker).stmt(0xc000a8d180, 0x0, {0xc58ed0, 0xc000130ae0})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/stmt.go:533 +0x1777
go/types.(*Checker).stmtList(0xc000a8d180, 0x0, {0xc000514080?, 0x5e9c60?, 0xc000a8d180?})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/stmt.go:121 +0x85
go/types.(*Checker).funcBody(0xc000a8d180, 0xc58c30?, {0xc0002941b4?, 0xa?}, 0xc000114fc0, 0xc000217560, {0x0?, 0x0?})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/stmt.go:41 +0x2f3
go/types.(*Checker).funcDecl.func1()
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/decl.go:888 +0x3a
go/types.(*Checker).processDelayed(0xc000a8d180, 0x0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/check.go:516 +0x15c
go/types.(*Checker).checkFiles(0xc000a8d180, {0xc0004ea030, 0x2, 0x2})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/check.go:462 +0x17e
go/types.(*Checker).Files(0xc0001da0e0?, {0xc0004ea030?, 0xc0004aa1e0?, 0x6?})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/go/types/check.go:422 +0x75
golang.org/x/tools/go/packages.(*loader).loadPackage(0xc0001da0e0, 0xc0000f9cb0)
        /home/bbkane/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:1052 +0xa32
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
        /home/bbkane/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:851 +0x1a9
sync.(*Once).doSlow(0x0?, 0x0?)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/sync/once.go:76 +0xb4
sync.(*Once).Do(...)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.23.1/libexec/src/sync/once.go:67
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x0?, 0x0?)
        /home/bbkane/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:839 +0x3b
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0x0?)
        /home/bbkane/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:846 +0x26
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1 in goroutine 306
        /home/bbkane/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:845 +0x94
```

**Comment by myysophia** [comment]
go-callvis --version
v0.7.0 built from git (unknown)


mee too

**Comment by ondrajz** [comment]
This issue ist most likely fixed in #202. Please test it to confirm it fixes your issues. Thank you.

**Comment by bbkane** [comment]
Yes! The following is working for me:

```bash
go install github.com/ofabry/go-callvis@master
~/go/bin/go-callvis .
```

A few notes:

Even though I installed from master and this fix is in place, the version is still wrong:

```
$ ~/go/bin/go-callvis -version
v0.7.0 built from git (unknown)
```

---

The README says graphviz is only an requirement if I use the `-graphviz` flag, but I also needed the `dot` command installed by `graphviz`.
```
$ ~/go/bin/go-callvis .
2025/01/01 14:41:29 http serving at http://localhost:7878
2025/01/01 14:41:29 converting dot to svg
2025/01/01 14:41:29 unable to find program 'dot', please install it or check your PATH
```

Thanks for making `go-callviz`, it's a fun way to visualize my code!

**Comment by ondrajz** [comment]
@bbkane I just released [v0.7.1](https://github.com/ondrajz/go-callvis/releases/tag/v0.7.1) with latest fixes. 

Regarding the graphviz part, if you build without CGO it will fallback to using graphviz from the system at the moment.

Thank you @bbkane for reporting.

**Comment by bbkane** [comment]
@ondrajz , do you want a PR to the README saying that the `dot` command is needed if built without CGO?

**Comment by ondrajz** [comment]
That would be great, go ahead, thanks.
